# 项目基本配置
基本设置:
  # 项目名称
  PROJECT_NAME: 项目管理中心

# 后端服务配置
后端:
  # 后端主机
  BACKEND_HOST: 0.0.0.0
  # 后端端口
  BACKEND_PORT: 8011
  # 后端启动命令
  BACKEND_CMD: .venv\Scripts\python -m uvicorn app.main:app --host {host} --port {port}
  # 后端窗口标题
  BACKEND_WINDOW: uvicorn_backend

# 前端服务配置
前端:
  # 前端主机
  FRONTEND_HOST: localhost
  # 前端端口
  FRONTEND_PORT: 8012
  # 前端启动命令
  FRONTEND_CMD: pnpm dev --port {port} --strictPort
  # 前端窗口标题
  FRONTEND_WINDOW: pnpm_frontend 